services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app-ppdbsula
    volumes:
      - .:/var/www/html
    networks:
      - app-bridge

  webserver:
    image: nginx:stable-alpine
    container_name: nginx-ppdbsula
    ports:
      - "8000:80"
      - "5173:5173"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf   # Menyambungkan file konfigurasi Nginx
      - .:/var/www/html   # Menyambungkan folder app ke dalam container
    depends_on:
      - app   # Nginx harus menunggu app (PHP-FPM) siap
    networks:
      - app-bridge

  redis:
    image: redis:latest
    container_name: redis-ppdbsula
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./redis:/data
    networks:
      - app-bridge

  mailpit:
    image: axllent/mailpit
    container_name: mailpit-ppdbsula
    ports:
      - "8025:8025"     # Web UI
      - "1025:1025"     # SMTP
    networks:
      - app-bridge

networks:
  app-bridge:
    external: true